# Generated by Django 4.2.3 on 2023-07-27 20:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_bot_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to=api.models.bot_directory_path),
        ),
    ]
