# Generated by Django 4.2.3 on 2023-10-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_bot_user_bot_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="initalised",
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
