# Generated by Django 4.2.3 on 2023-10-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_bot_initalised"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="initalised",
            field=models.BooleanField(),
        ),
    ]
